# Site settings
title: SCSE-OFFSEC Recruitment 2018
description: NTU Inititated Cyber Security Interest Group
baseurl: "/recruitment2018" # the subpath of your site, e.g. /blog
url: "https://ntu-offsec.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SCSE-offsec
user_description: Founded in <a href="https://sg.linkedin.com/in/sayedhamzah">2015</a>, we are an NTU student initiated interest group that is under the care of SCSE Computer Science and Engineering Club (CSEC).
user_title: Recruitment CTF 2018
email: scse-offseclub@e.ntu.edu.sg
email2: ntu.offsec@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
fburl: https://www.facebook.com/ntu.offsec/
githuburl: https://github.com/ntu-offsec/
homeurl: https://ntu-offsec.github.io/blog/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
